<?php
/**
 * Created by c5game.com
 * User: tongsiqi@c5game.com
 * Date: 2018/7/7
 * Time: 20:31
 */
namespace app\controllers;

use yii\web\Controller;

class BasicController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}