<?php
/**
 * Created by tongsq.
 * Date: 2018/3/12
 * Time: 10:51
 */
namespace app\components;

use Yii;
use yii\base\ActionFilter;

class ActionTimeFilter extends ActionFilter
{
    private $_startTime;

    public function beforeAction($action)
    {
        $this->_startTime = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $time = microtime(true) - $this->_startTime;
        Yii::trace("Action '{$action->uniqueId}' spent $time second.");
        $logPath = Yii::getAlias('@app/log/request_time.log');
        file_put_contents($logPath, Yii::$app->controller->getRoute() . "\t" . $time . "\n", FILE_APPEND);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}